export { BrandMark } from "./BrandMark";
export { Button } from "./Button";
export { Badge } from "./Badge";
export { ScoreGauge } from "./ScoreGauge";
export { ScoreCard } from "./ScoreCard";
export { ComparisonTable } from "./ComparisonTable";
export { NavBar } from "./NavBar";
export { Footer } from "./Footer";
export { ScanInput } from "./ScanInput";
export { RankedFix } from "./RankedFix";
export { PositioningMirror } from "./PositioningMirror";
export { SearchGapTable } from "./SearchGapTable";
export { AppShell } from "./AppShell";
export { KpiCard } from "./KpiCard";
export { UnlockBand } from "./UnlockBand";
export { ScanningRing } from "./ScanningRing";
export { CompareCard } from "./CompareCard";
export { TeardownCard } from "./TeardownCard";
export { Testimonial } from "./Testimonial";
export { FaqItem } from "./FaqItem";
export { Alert } from "./Alert";
export { FeatureStep } from "./FeatureStep";
export { TextField } from "./TextField";
export { Tabs } from "./Tabs";
export { PricingTable } from "./PricingTable";
export { LandingHero } from "./LandingHero";
export { ResultsScreen } from "./ResultsScreen";
export { DashboardScreen } from "./DashboardScreen";
export { ChannelDonut } from "./ChannelDonut";
export { TrafficByChannel } from "./TrafficByChannel";
export { CompetitorEdgePanel } from "./CompetitorEdgePanel";
export { CompetitorGapMap } from "./CompetitorGapMap";
export { ReferrerRow } from "./ReferrerRow";
export { EvidenceDrawer } from "./EvidenceDrawer";
export { IntentRecencyMap } from "./IntentRecencyMap";
export { BuyerThreadFeed } from "./BuyerThreadFeed";
export { PlanItemCard } from "./PlanItemCard";
export { LeverBanner } from "./LeverBanner";
export { ProgressChart } from "./ProgressChart";
export { CompanyTicker } from "./CompanyTicker";
export { StorySection } from "./StorySection";
export { HowItWorks } from "./HowItWorks";
export { ActionEngine } from "./ActionEngine";
export { WhySwitch } from "./WhySwitch";
export { Testimonials } from "./Testimonials";
export { Audience } from "./Audience";
export { PlanCards } from "./PlanCards";
export { PageHeader } from "./PageHeader";
export { ComingSoon } from "./ComingSoon";
export { PricingBlock } from "./PricingBlock";
export { ScoreTravels } from "./ScoreTravels";
export { FinalCta } from "./FinalCta";

// Self-contained preview runtime: render any export with the SAME bundled React,
// so preview cards need no external/vendored React (avoids cross-instance errors).
import * as __React from "react";
import { createRoot as __createRoot } from "react-dom/client";
export function mount(Comp: any, props: any, el: any) {
  __createRoot(el).render(__React.createElement(Comp, props));
}
export { PlanScreen } from "./PlanScreen";
export { CompetitorsScreen } from "./CompetitorsScreen";
export { ProgressScreen } from "./ProgressScreen";
export { LandingScreen } from "./LandingScreen";
export { PricingScreen } from "./PricingScreen";
export { CustomersScreen } from "./CustomersScreen";
export { SettingsScreen } from "./SettingsScreen";
export { OnboardingScreen } from "./OnboardingScreen";
export { ScanningScreen } from "./ScanningScreen";
export { GalleryScreen } from "./GalleryScreen";
export { TeardownsScreen } from "./TeardownsScreen";
export { CompareScreen } from "./CompareScreen";
export { AboutScreen } from "./AboutScreen";
export { ContactScreen } from "./ContactScreen";
export { ToolsScreen } from "./ToolsScreen";
export { RoadmapScreen } from "./RoadmapScreen";
export { StatusScreen } from "./StatusScreen";
export { LegalScreen } from "./LegalScreen";
