/**
 * SYNTH stage (Task 5) — Sonnet reads the 4 fact sheets and produces:
 *   - PositioningMirror   (listing vs. reviews gap)
 *   - exactly 3 Findings  (evidence-linked, one per growth category)
 *   - 1 SampleAction      (with a ready-to-use draft)
 *
 * §13: Sonnet reads FACT SHEETS ONLY, never raw text.
 * Fixture-aware: when fixturesEnabled()=true, returns fixtureSynth() without any LLM call.
 */

import { callModel } from "@/lib/llm/anthropic";
import { extractJson } from "@/lib/llm/json";
import { SYNTH_SYSTEM, buildSynthPrompt, SYNTH_SYSTEM_LITE, buildSynthPromptLite } from "@/lib/llm/prompts";
import { getFreshFactSheet, factSheetSubjectType } from "@/lib/scan/fact-sheets";
import { fixtures } from "@/lib/scan/fixture-seam";
import type { ScanContext } from "@/lib/scan/pipeline";
import type { ModelId } from "@/lib/telemetry/pipeline-runs";
import type {
  SynthResult,
  Finding,
  PositioningMirror,
  SampleAction,
  ReviewThemesSheet,
  PositioningSheet,
  CompetitorGapSheet,
  KeywordSheet,
  MarketTierSeeds,
  CategoryNicheSeeds,
  LadderSeeds,
} from "@/lib/llm/types";

export type { MarketTierSeeds } from "@/lib/llm/types";

/** The deep (paid) synth: Sonnet writes the findings the paid action plan is built
 *  FROM (generateActions), so it stays on the stronger model. */
export const SYNTH_MODEL_FULL: ModelId = "claude-sonnet-4-6";
/** The free-tier TEASER synth: Haiku 4.5, run in `lite` mode (positioning mirror +
 *  category seeds only). Measured on THIS pipeline Haiku runs ~2× faster (≈92 vs
 *  ≈45 tok/s) and ~3× cheaper ($1/$5 vs $3/$15 per MTok) than Sonnet; lite cuts
 *  the output ~800→~280 tokens (the real latency lever). The free report renders
 *  only these two fields; the full findings that drive the PAID plan are
 *  regenerated by the deep pass on `SYNTH_MODEL_FULL`. Guard: synth.model.test.ts. */
export const SYNTH_MODEL_FREE: ModelId = "claude-haiku-4-5-20251001";

// ---------------------------------------------------------------------------
// Minimal valid fallback when JSON parsing fails
// ---------------------------------------------------------------------------
const DEGRADED_MIRROR: PositioningMirror = {
  listingSays: "",
  reviewsValue: "",
  gap: "",
};

const DEGRADED_FINDING: Finding = {
  category: "content",
  claim:
    "Your strongest discoverability lever right now is your own page: lead with one specific outcome and your highest-intent keyword in the title and first screen.",
  basis: "probability_based",
  confidence: 0.4,
  evidence: [{ excerpt: "(derived from your site)", source: "positioning" }],
};

const DEGRADED_SAMPLE_ACTION: SampleAction = {
  category: "content",
  title: "Sharpen your homepage headline around one outcome + one keyword",
  why: "A specific, keyword-aligned headline is the fastest discoverability win for an early-stage site.",
  draft: "",
};

// Always-insight fallback: when the model output truly can't be used, still
// reflect the user's REAL site (the positioning fact sheet) instead of an error.
// The free scan must deliver value whenever the app is live and available.
function buildDegradedResult(positioning?: PositioningSheet): SynthResult {
  const claims = (positioning?.claims ?? []).filter((s) => typeof s === "string" && s.trim().length > 0);
  const valueProps = (positioning?.valueProps ?? []).filter((s) => typeof s === "string" && s.trim().length > 0);
  const listingSays = [...claims, ...valueProps].slice(0, 3).join(" · ");
  if (!listingSays) {
    return { positioningMirror: DEGRADED_MIRROR, findings: [DEGRADED_FINDING], sampleAction: DEGRADED_SAMPLE_ACTION };
  }
  const lead = (claims[0] ?? valueProps[0] ?? "").slice(0, 160);
  return {
    positioningMirror: {
      listingSays,
      reviewsValue: "",
      gap: "This scan ran in early-stage mode with limited external signal, so this reflects what your site says about itself. As reviews, search demand and community mentions accrue, the gap analysis sharpens.",
    },
    findings: [
      {
        category: "content",
        claim: `Your site leads with “${lead}”. Make your single highest-intent keyword and one concrete outcome promise appear in the page title and first screen — the fastest discoverability win for an early-stage site.`,
        basis: "probability_based",
        confidence: 0.5,
        evidence: [{ excerpt: lead, source: "positioning" }],
      },
    ],
    sampleAction: DEGRADED_SAMPLE_ACTION,
  };
}

// ---------------------------------------------------------------------------
// Type guards for parsed model output
// ---------------------------------------------------------------------------
function isValidFinding(f: unknown): f is Finding {
  if (typeof f !== "object" || f === null) return false;
  const obj = f as Record<string, unknown>;
  return (
    typeof obj["claim"] === "string" &&
    Array.isArray(obj["evidence"]) &&
    (obj["evidence"] as unknown[]).length > 0 &&
    typeof obj["category"] === "string" &&
    typeof obj["confidence"] === "number"
  );
}

function isValidPositioningMirror(m: unknown): m is PositioningMirror {
  if (typeof m !== "object" || m === null) return false;
  const obj = m as Record<string, unknown>;
  return (
    typeof obj["listingSays"] === "string" &&
    typeof obj["reviewsValue"] === "string" &&
    typeof obj["gap"] === "string"
  );
}

function isValidSampleAction(a: unknown): a is SampleAction {
  if (typeof a !== "object" || a === null) return false;
  const obj = a as Record<string, unknown>;
  return (
    typeof obj["title"] === "string" &&
    typeof obj["why"] === "string" &&
    typeof obj["draft"] === "string" &&
    typeof obj["category"] === "string"
  );
}

/** Sanitise an LLM string array: keep non-empty trimmed strings, cap the count. */
function strArray(v: unknown, cap: number): string[] {
  if (!Array.isArray(v)) return [];
  return v
    .map((x) => (typeof x === "string" ? x.trim() : ""))
    .filter((s) => s.length >= 2 && s.length <= 60)
    .slice(0, cap);
}

/**
 * Pure parse of an already-decoded synth object (no JSON.parse/extractJson) — the
 * SAME parse shared by the full and lite synth (the lite call just omits
 * findings/sampleAction, which degrade to safe defaults). Exported so tests can
 * exercise parsing directly against an object, and named for the lite path since
 * that's the free-tier surface M1 (market-tier seeds) lands on.
 */
export function parseLiteSynth(obj: unknown): SynthResult {
  const o = (typeof obj === "object" && obj !== null ? obj : {}) as Record<string, unknown>;

  const mirror: PositioningMirror = isValidPositioningMirror(o["positioningMirror"])
    ? o["positioningMirror"]
    : DEGRADED_MIRROR;
  // Attach LLM-authored audience tags (optional) onto the mirror, sanitised.
  const pm = (o["positioningMirror"] ?? {}) as Record<string, unknown>;
  const intendedAudience = strArray(pm["intendedAudience"], 5);
  const actualAudience = strArray(pm["actualAudience"], 5);
  if (intendedAudience.length > 0) mirror.intendedAudience = intendedAudience;
  if (actualAudience.length > 0) mirror.actualAudience = actualAudience;
  // P2 (2026-07-20, data board): the two-label category/niche seed. Parsed
  // independently of the legacy `categorySeeds`/`marketTiers` keys below — a
  // synth object may carry EITHER shape (new prompt output) OR the old flat
  // shape (a stale cached call, an older test fixture) and both parse safely
  // through this ONE function, never a forked parser (RC1).
  const parseLadderSeeds = (v: unknown): LadderSeeds | null => {
    if (typeof v !== "object" || v === null) return null;
    const o2 = v as Record<string, unknown>;
    const label = typeof o2["label"] === "string" ? o2["label"].trim().slice(0, 60) : "";
    const phrases = strArray(o2["phrases"], 6);
    if (!label && phrases.length === 0) return null;
    return { label, phrases };
  };
  const categoryRaw = parseLadderSeeds(o["category"]);
  const nicheRaw = parseLadderSeeds(o["niche"]);
  const categoryNiche: CategoryNicheSeeds | undefined =
    categoryRaw && nicheRaw ? { category: categoryRaw, niche: nicheRaw } : undefined;

  // categorySeeds: legacy top-level key wins when present (a truly old cached
  // payload); otherwise DERIVED from categoryNiche.category.phrases so
  // consumers that haven't migrated to read categoryNiche directly (yet) keep
  // working unchanged (CLAUDE.md "fix the class, keep the process simple" —
  // one parse, not a second code path per consumer).
  const legacyCategorySeeds = strArray(o["categorySeeds"], 5);
  const categorySeeds = legacyCategorySeeds.length > 0 ? legacyCategorySeeds : (categoryNiche?.category.phrases ?? []);

  // M1: labeled broad/niche market-tier seeds (optional — absent on legacy
  // output). Same sanitisation as categorySeeds, capped at 4 per tier. A
  // `medium` key may still be present on an older/legacy synth object — it is
  // simply ignored (never priced/rendered since bb6ef07 removed that rung).
  // P2: when the LLM output carries the new category/niche shape and no
  // legacy `marketTiers` key, DERIVE the same broad/niche seed shape from it
  // (broad←category.phrases, niche←niche.phrases) — back-compat for the
  // existing `computeMarketTiers` ladder/render pathway, which is untouched
  // by P2 (it renders TODAY; the new laddered categoryCard/nicheCard is a
  // data-only addition this phase, P3 renders it).
  const tiersRaw = (o["marketTiers"] ?? null) as Record<string, unknown> | null;
  const legacyMarketTiers: MarketTierSeeds | undefined =
    tiersRaw && typeof tiersRaw === "object"
      ? {
          broad: strArray(tiersRaw["broad"], 4),
          niche: strArray(tiersRaw["niche"], 4),
        }
      : undefined;
  const marketTiers: MarketTierSeeds | undefined =
    legacyMarketTiers ??
    (categoryNiche
      ? { broad: categoryNiche.category.phrases.slice(0, 4), niche: categoryNiche.niche.phrases.slice(0, 4) }
      : undefined);

  const rawFindings = Array.isArray(o["findings"]) ? (o["findings"] as unknown[]) : [];
  const validFindings: Finding[] = rawFindings.filter(isValidFinding).map((f) => ({
    ...f,
    // Clamp confidence to [0, 1] so values like 99 don't overflow numeric(3,2)
    confidence: Math.max(0, Math.min(1, Number(f.confidence))),
  }));
  const findings: Finding[] = validFindings.length > 0 ? validFindings : [DEGRADED_FINDING];

  const sampleAction: SampleAction = isValidSampleAction(o["sampleAction"])
    ? o["sampleAction"]
    : DEGRADED_SAMPLE_ACTION;

  return { positioningMirror: mirror, findings, sampleAction, categorySeeds, marketTiers, categoryNiche };
}

export function parseSynthResult(text: string): SynthResult | null {
  let parsed: unknown;
  try {
    parsed = JSON.parse(extractJson(text));
  } catch {
    return null;
  }

  if (typeof parsed !== "object" || parsed === null) return null;
  return parseLiteSynth(parsed);
}

// ---------------------------------------------------------------------------
// Fact-sheet helpers: read and serialise for prompt injection
// ---------------------------------------------------------------------------
async function readSheet<T>(
  subjectType: string,
  subjectKey: string,
  kind: "review_themes" | "positioning" | "competitor_gap" | "keyword_data",
  fallback: T,
): Promise<T> {
  try {
    const row = await getFreshFactSheet(subjectType, subjectKey, kind);
    if (row === null) return fallback;
    return row.body as T;
  } catch {
    return fallback;
  }
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------
export async function runSynth(
  ctx: ScanContext,
  opts: { model?: ModelId; lite?: boolean } = {},
): Promise<SynthResult> {
  const model = opts.model ?? SYNTH_MODEL_FULL;
  // Fixture path — no LLM call, no fact-sheet reads
  const _f = fixtures();
  if (_f) {
    return _f.synth();
  }

  // Read the 4 fact sheets (degrade gracefully on missing/expired sheets)
  // Use factSheetSubjectType so web-mode reads "web" sheets (matching extract's write).
  const subjectType = factSheetSubjectType(ctx.mode);
  const [reviewThemesBody, positioningBody, competitorGapBody, keywordDataBody] =
    await Promise.all([
      readSheet<ReviewThemesSheet>(subjectType, ctx.storeUrl, "review_themes", { themes: [] }),
      readSheet<PositioningSheet>(subjectType, ctx.storeUrl, "positioning", { category: "", claims: [], valueProps: [] }),
      readSheet<CompetitorGapSheet>(subjectType, ctx.storeUrl, "competitor_gap", { competitors: [] }),
      readSheet<KeywordSheet>(subjectType, ctx.storeUrl, "keyword_data", { clusters: [] }),
    ]);

  // LITE (free teaser): generate ONLY the two rendered fields (positioning mirror
  // + category seeds) — the findings/sampleAction that drive the PAID plan are
  // regenerated by the deep pass on the full model. Cutting the output ~800 tokens
  // → ~280 is the real latency lever (generation time ∝ output tokens). Doesn't
  // read keyword_data (the mirror + seeds don't use it).
  const prompt = opts.lite
    ? buildSynthPromptLite({
        reviewThemes: JSON.stringify(reviewThemesBody, null, 2),
        positioning: JSON.stringify(positioningBody, null, 2),
        competitorGap: JSON.stringify(competitorGapBody, null, 2),
      }, { storeUrl: ctx.storeUrl })
    : buildSynthPrompt({
        reviewThemes: JSON.stringify(reviewThemesBody, null, 2),
        positioning: JSON.stringify(positioningBody, null, 2),
        competitorGap: JSON.stringify(competitorGapBody, null, 2),
        keywordData: JSON.stringify(keywordDataBody, null, 2),
      }, { storeUrl: ctx.storeUrl });

  let text: string;
  try {
    const result = await callModel({
      model,
      system: opts.lite ? SYNTH_SYSTEM_LITE : SYNTH_SYSTEM,
      prompt,
      scanId: ctx.scanId,
      stage: "synth",
      maxTokens: opts.lite ? 1024 : 4096,
    });
    text = result.text;
  } catch {
    return buildDegradedResult(positioningBody);
  }

  const parsed = parseSynthResult(text);
  if (!parsed) return buildDegradedResult(positioningBody);

  // GROUNDING (invariant #11): the review sheet is the ONLY evidence for the
  // positioning mirror's review claims. When it has zero themes, the mirror must
  // be empty — never a plausible synthesis. The extract layer already refuses to
  // invent reviews (prompts.ts:62 "If there are no reviews, return { themes: [] }");
  // this closes the same guard at synth, where a fabricated paragraph otherwise
  // passes parseSynthResult (it validates types, not grounding). This is the fix
  // for the invented reviews on the unlaunched reachkit.app (scan 6d49d58e).
  if (reviewThemesBody.themes.length === 0) {
    parsed.positioningMirror = {
      ...parsed.positioningMirror,
      reviewsValue: "",
      actualAudience: [],
    };
  }
  return parsed;
}
