// tests/generate/rules/people.test.ts — BUILD §8 hard rule 2, the half a
// pattern can decide.
//
// The other half is enforced by the absence of a field: `drafts` has no
// author, byline, bio, persona or contributor column, so a generated byline
// has nowhere to be written to. `tests/generate/migrations.test.ts` is
// where that absence is asserted; this suite is the scanning half.
import "../env";
import { describe, expect, it } from "vitest";
import {
  checkInventedPeople,
  checkUnsourcedTestimonial,
} from "../../../src/lib/generate/rules/people";

describe("§8 hard rule 2 — a quoted remark attributed to someone must link a page naming them", () => {
  it("a block quote attributed to a named third party with no link fails", () => {
    const markdown = "> This changed how our whole team works, week one.\n> — Dana Whitfield";
    expect(checkInventedPeople({ markdown, businessName: "Acme" })?.rule).toBe("no_invented_people");
  });

  it("the same block with a link in the same block passes", () => {
    const markdown =
      "> This changed how our whole team works, week one.\n> — Dana Whitfield, [in the write-up](https://press.example/piece)";
    expect(checkInventedPeople({ markdown, businessName: "Acme" })).toBeNull();
  });

  it("a quotation attributed to the customer's own business name needs no link", () => {
    const markdown = '"We built the seat limit in on purpose, and we keep it," says Acme.';
    expect(checkInventedPeople({ markdown, businessName: "Acme" })).toBeNull();
  });

  it("the same quotation attributed to a stranger fails", () => {
    const markdown = '"We built the seat limit in on purpose, and we keep it," says Dana Whitfield.';
    expect(checkInventedPeople({ markdown, businessName: "Acme" })?.rule).toBe("no_invented_people");
  });

  it("a site with no recorded name has nobody who needs no link — an attribution still fails", () => {
    const markdown = '"We built the seat limit in on purpose, and we keep it," says Acme.';
    expect(checkInventedPeople({ markdown, businessName: null })?.rule).toBe("no_invented_people");
  });

  it("ordinary prose naming a person, with no quotation, is not this rule's business", () => {
    const markdown = "Dana Whitfield wrote the standard this section follows.";
    expect(checkInventedPeople({ markdown, businessName: "Acme" })).toBeNull();
  });
});

describe("§8 hard rule 2 — an unsourced testimonial fails whether or not it names a speaker", () => {
  it("an endorsement-shaped block naming nobody and linking nothing fails", () => {
    const markdown = "Our customers say it pays for itself in a month.";
    expect(checkUnsourcedTestimonial({ markdown })?.rule).toBe("no_unsourced_testimonial");
  });

  it("a review-shaped block with a link in the same block passes", () => {
    const markdown = "Reviews are collected on [an independent site](https://reviews.example/acme).";
    expect(checkUnsourcedTestimonial({ markdown })).toBeNull();
  });

  it("an unattributed block quote that is a remark still fails — a reported remark is a testimonial", () => {
    const markdown = "> It took about ten minutes to move everything across and nothing broke.";
    expect(checkUnsourcedTestimonial({ markdown })?.rule).toBe("no_unsourced_testimonial");
  });

  it("a page with no remark and no endorsement passes", () => {
    const markdown = "Count the people who need a seat, then read the plan that covers them.";
    expect(checkUnsourcedTestimonial({ markdown })).toBeNull();
  });
});
