// BUILD §8 hard rule 2 — no invented people.
//
// "No generated bylines/bios/personas. Customer identity or none."
//
// **Half of this rule is enforced by the absence of a field.** There is no
// author, byline, bio, persona or contributor column on `drafts` and none in
// any destination payload: a generated byline has nowhere to be written to.
// The one attribution a page may carry is `drafts.attribution`, copied from
// the name recorded for the site and from nowhere else, and a site that
// records no name publishes with no attribution rather than a generated one.
//
// **The other half is what a pattern can decide.** Recognising an invented
// person inside prose needs entity recognition and would be probabilistic —
// exactly what "enforced in code, not prompts" rules out. So the scanning
// half is narrowed to two shapes that can be decided lexically:
//
//   * a quoted remark — quotation marks or a block quote — attributed to
//     anyone other than the customer, with no link in the same block;
//   * a testimonial-, review- or endorsement-shaped block with no link in
//     the same block, whether or not it names a speaker.
//
// A persona named only in body prose, with no quotation and no attribution,
// is not caught here. It is caught by the grounding rule where it makes a
// claim, and the residual is stated rather than papered over.
import { blocksOf } from "./text";
import type { RuleFailure } from "./types";

/** Long enough to be a remark rather than a quoted term. */
const REMARK_MIN_CHARS = 25;

/** A remark set in quotation marks — straight or typographic. */
const QUOTED_REMARK_RE = new RegExp(`["\u201c]([^"\u201d]{${REMARK_MIN_CHARS},})["\u201d]`);

/** "— Someone", "says Someone", "according to Someone": the shapes an
 *  attribution takes beside a remark. The captured group is the name. */
const ATTRIBUTION_RES: readonly RegExp[] = Object.freeze([
  /[—–-]{1,2}\s*([A-Z][\p{L}'’.-]+(?:\s+[A-Z][\p{L}'’.-]+){0,3})/u,
  /\b(?:says|said|explains|explained|notes|noted|adds|added|according to|told us)\s+([A-Z][\p{L}'’.-]+(?:\s+[A-Z][\p{L}'’.-]+){0,3})/u,
]);

/** The words that make a block testimonial-, review- or endorsement-shaped.
 *  A closed list: a form found later is added here. */
const TESTIMONIAL_WORDS: readonly string[] = Object.freeze([
  "testimonial",
  "review",
  "reviews",
  "endorsement",
  "endorses",
  "endorsed",
  "customers say",
  "clients say",
  "users say",
  "rated us",
  "gave us",
  "star rating",
  "five stars",
  "5 stars",
  "recommends us",
  "would recommend",
  "our customers",
]);

/** The customer's own attribution needs no link. Matched against the
 *  business name recorded for the site, whole and case-insensitively. */
function isTheCustomer(name: string, businessName: string | null): boolean {
  const own = businessName?.trim().toLowerCase() ?? "";
  if (own.length === 0) return false;
  const candidate = name.trim().toLowerCase();
  return candidate === own || own.includes(candidate) || candidate.includes(own);
}

function attributedName(text: string): string | null {
  for (const pattern of ATTRIBUTION_RES) {
    const match = pattern.exec(text);
    if (match?.[1] !== undefined) return match[1];
  }
  return null;
}

export function checkInventedPeople(a: {
  markdown: string;
  businessName: string | null;
}): RuleFailure | null {
  for (const block of blocksOf(a.markdown)) {
    if (block.hasLink) continue;
    const isRemark = block.quoted || QUOTED_REMARK_RE.test(block.text);
    if (!isRemark) continue;
    const name = attributedName(block.text);
    if (name === null) continue;
    if (isTheCustomer(name, a.businessName)) continue;
    return { rule: "no_invented_people" };
  }
  return null;
}

export function checkUnsourcedTestimonial(a: { markdown: string }): RuleFailure | null {
  for (const block of blocksOf(a.markdown)) {
    if (block.hasLink) continue;
    const haystack = block.text.toLowerCase();
    if (TESTIMONIAL_WORDS.some((word) => haystack.includes(word))) {
      return { rule: "no_unsourced_testimonial" };
    }
    // A block quote long enough to be a remark, carrying no link, is a
    // reported remark whether or not it names its speaker — the `>` is the
    // quotation, so no quotation mark is looked for inside it.
    if (block.quoted && block.text.trim().length >= REMARK_MIN_CHARS) {
      return { rule: "no_unsourced_testimonial" };
    }
  }
  return null;
}
