// tests/generate/migrations.test.ts — the two `drafts` migrations BUILD §8
// and §10 need, asserted against their own text.
//
// A migration added in a feature PR has no way to get a live-schema test:
// the `db` vitest project's `include` is `LIVE_SCHEMA_TESTS` in
// `vitest.config.ts`, which is an owner file. This suite therefore follows
// `tests/db/domainblocks.test.ts`'s precedent — assert the migration's own
// SQL, with comment lines stripped first so prose *describing* a column can
// never satisfy an assertion *about* it. The behaviour itself was exercised
// by hand against a scratch database; the transcript is in the PR.
//
// Two of the assertions below are about something that is **not** there:
// there is no author, byline, bio, persona or contributor column, and that
// absence is how §8's "no invented people" is enforced. A test that only
// checked the columns that exist would let someone add one.
import "./env";
import { readFileSync } from "node:fs";
import path from "node:path";
import { describe, expect, it } from "vitest";
import { topicOf } from "../../src/lib/db/topics";

const MIGRATIONS = path.resolve(import.meta.dirname, "../../supabase/migrations");

const CORE = "20260906120000_drafts_core.sql";
const CLAIMS = "20260906120100_drafts_claims.sql";

/** The SQL with every `--` comment line removed, so prose about a column
 *  never satisfies an assertion about the column. */
function sqlOf(name: string): string {
  return readFileSync(path.join(MIGRATIONS, name), "utf8")
    .split("\n")
    .filter((line) => !line.trimStart().startsWith("--"))
    .join("\n");
}

describe("both migrations carry an assigned topic token", () => {
  it("`drafts_core` resolves to its sub-token, not to the parent `drafts` topic", () => {
    expect(topicOf(CORE)).toEqual({ token: "drafts_core", owner: "BP-042" });
  });

  it("`drafts_claims` resolves to its own sub-token", () => {
    expect(topicOf(CLAIMS)).toEqual({ token: "drafts_claims", owner: "BP-043" });
  });
});

describe("BUILD §9's state machine is a closed set on the column", () => {
  const sql = sqlOf(CORE);

  it("all ten states are admitted and no eleventh is", () => {
    const match = /drafts_state_closed check \(\s*state in \(([^)]*)\)/s.exec(sql);
    expect(match).not.toBeNull();
    const states = [...(match?.[1] ?? "").matchAll(/'([a-z_]+)'/g)].map((m) => m[1]);
    expect(states.sort()).toEqual(
      [
        "approved",
        "failed",
        "generating",
        "in_review",
        "needs_attention",
        "planned",
        "published",
        "publishing",
        "skipped",
        "unpublished",
      ].sort()
    );
  });
});

describe("BUILD §8 hard rule 1 — the grounded passage is written once", () => {
  const sql = sqlOf(CORE);

  it("a trigger fires before every update on `drafts`", () => {
    expect(sql).toMatch(/create trigger drafts_passage_immutable\s+before update on drafts/);
  });

  it("it compares the passage, and raises when it changed", () => {
    expect(sql).toContain("old.grounded_fact ->> 'passage'");
    expect(sql).toContain("new.grounded_fact ->> 'passage'");
    expect(sql).toContain("raise exception");
  });

  it("only the passage is frozen — the url and read date stay correctable", () => {
    expect(sql).not.toMatch(/old\.grounded_fact\s+is distinct from\s+new\.grounded_fact/);
  });
});

describe("BUILD §8 hard rule 2 — there is nowhere to write a generated byline", () => {
  const sql = sqlOf(CORE);

  it("adds exactly one attribution column and no author, byline, bio, persona or contributor column", () => {
    expect(sql).toMatch(/add column if not exists attribution text/);
    for (const forbidden of ["author", "byline", "bio", "persona", "contributor"]) {
      expect(sql).not.toMatch(new RegExp(`add column[^;]*\\b${forbidden}\\b`, "i"));
    }
  });
});

describe("BUILD §8 hard rule 4 — the recovery count and the failures survive their run", () => {
  const sql = sqlOf(CORE);

  it("`hard_rule_attempts` defaults to zero and is bounded at two — one attempt and its one regeneration", () => {
    expect(sql).toMatch(/hard_rule_attempts smallint not null default 0/);
    expect(sql).toMatch(/hard_rule_attempts >= 0 and hard_rule_attempts <= 2/);
  });

  it("`rule_failures` is a jsonb column, so the cause a rejected day carries outlives the run", () => {
    expect(sql).toMatch(/add column if not exists rule_failures jsonb/);
  });
});

describe("BUILD §8 hard rule 4 — the claim verdict, and nothing that could go stale", () => {
  const sql = sqlOf(CLAIMS);

  it("adds `claim_check jsonb` and nothing else", () => {
    expect(sql).toMatch(/add column if not exists claim_check jsonb/);
    expect(sql.match(/add column/g) ?? []).toHaveLength(1);
  });

  it("adds no `outstanding` column, no `recheck_due` flag, no queue table and no version on `sites`", () => {
    // The index is *named* for the state it selects; what must not exist is
    // a column or a flag holding it, which is what could go stale.
    for (const forbidden of ["outstanding", "recheck_due", "version"]) {
      expect(sql.toLowerCase()).not.toMatch(new RegExp(`add column[^;]*\\b${forbidden}\\b`));
    }
    expect(sql.toLowerCase()).not.toContain("create table");
    expect(sql.toLowerCase()).not.toContain("alter table sites");
  });

  it("the partial index holds a draft with no check at all — `is distinct from`, not `<>`", () => {
    expect(sql).toMatch(/where \(claim_check ->> 'state'\) is distinct from 'passed'/);
  });
});
