-- BUILD §8, §9, §10 — the drafts table's generation shape.
--
-- The baseline created `drafts` loosely (`00000000000001_baseline.sql`):
-- every column §10 names, `state text not null` with no check, and the
-- site-scoped RLS policies. This migration is §8's own shape on top of it,
-- and everything below is an invariant the database holds rather than one
-- application code restates:
--
--   * `state` is §9's ten-member enum, closed here.
--   * `grounded_fact->>'passage'` can never be rewritten (§8 hard rule 1:
--     "carried with its source URL + read date" — a statement the customer
--     can still read against needs the copy to be unarguable).
--   * there is **no author, byline, bio, persona or contributor column
--     anywhere**. That absence is how §8 hard rule 2 ("no invented people")
--     is enforced: a generated byline has nowhere to be written to. The one
--     attribution a page may carry is `attribution`, copied from the name
--     recorded for the site and from nowhere else.
--
-- Topic token `drafts`, sub-token `drafts_core` (`src/lib/db/topics.ts`).
--
-- `drafts` has no writer on disk before this migration, so the constraints
-- below run against an empty table and no backfill is invented to satisfy
-- them.

-- ── Columns ────────────────────────────────────────────────────────────

-- The page is titled by the pipeline, not at planning time; a row is
-- written when generation starts and the title arrives with the draft step.
alter table drafts alter column title drop not null;

-- The business name or account-holder name recorded for the site, copied at
-- generation. Null where the site records neither — the page then publishes
-- with no attribution rather than a generated one.
alter table drafts add column if not exists attribution text;

-- The count `recoveryOutcome` reads. **Automatic** attempts only: a
-- customer-started retry never increments it (DECISIONS 2026-08-31 ADR-070,
-- "one automatic regeneration").
alter table drafts add column if not exists hard_rule_attempts smallint not null default 0;

-- The last hard-rule battery's `RuleFailure[]`, so the cause a rejected day
-- may carry survives the run that produced it.
alter table drafts add column if not exists rule_failures jsonb;

alter table drafts add constraint drafts_hard_rule_attempts_bounded check (
  hard_rule_attempts >= 0 and hard_rule_attempts <= 2
);

-- ── §9's state machine, as a closed set ────────────────────────────────
--
-- The ten states BUILD §9 draws:
--   planned → generating → in_review → approved → publishing → published
--   in_review ↓ veto → skipped
--   publishing ↓ fail → failed → retry ×3 → needs_attention
--   published → unpublished
-- The transition table itself is the publishing engine's; this constraint
-- only closes the set of values a column may hold.
alter table drafts add constraint drafts_state_closed check (
  state in (
    'planned', 'generating', 'in_review', 'approved', 'publishing',
    'published', 'skipped', 'failed', 'needs_attention', 'unpublished'
  )
);

-- ── The grounded fact is written once ──────────────────────────────────
--
-- §8 hard rule 1: at least one verifiable fact from the customer's own live
-- pages, "carried with its source URL + read date". The passage is copied
-- word for word from the content fetched that day, and the promise is that
-- it can still be read against after the customer's own page has moved on.
-- That promise is only worth something if the copy cannot be edited later,
-- so the trigger — not a convention — is the invariant. The url and the
-- read date may still be corrected; only the passage is frozen.

create or replace function drafts_passage_is_immutable()
returns trigger
language plpgsql
as $$
begin
  if old.grounded_fact is not null
     and (old.grounded_fact ->> 'passage') is distinct from (new.grounded_fact ->> 'passage') then
    raise exception
      'drafts.grounded_fact->>''passage'' is written once and never rewritten (BUILD §8 hard rule 1)';
  end if;
  return new;
end;
$$;

create trigger drafts_passage_immutable
  before update on drafts
  for each row
  execute function drafts_passage_is_immutable();

-- ── Reads the generation engine makes ──────────────────────────────────
--
-- The comparison set's queued half, and the day a draft is scheduled for,
-- are both read per site.
create index if not exists idx_drafts_site_state on drafts (site_id, state);
create index if not exists idx_drafts_site_scheduled_for on drafts (site_id, scheduled_for);
